In [1]:
import numpy as np

In [2]:
x1 = np.array([8,4,7], ndmin=2).T
x2 = np.array([2,8,1], ndmin=2).T
x3 = np.array([3,1,1], ndmin=2).T
x4 = np.array([9,7,4], ndmin=2).T

In [3]:
barX = (x1+x2+x3+x4)/4
barX

array([[5.5 ],
       [5.  ],
       [3.25]])

In [4]:
1/4* (x1*x1.T + x2*x2.T + x3*x3.T + x4*x4.T) - barX*barX.T

array([[9.25  , 1.    , 6.375 ],
       [1.    , 7.5   , 0.    ],
       [6.375 , 0.    , 6.1875]])

In [5]:
barX @ barX.T

array([[30.25  , 27.5   , 17.875 ],
       [27.5   , 25.    , 16.25  ],
       [17.875 , 16.25  , 10.5625]])

In [6]:

x1.shape

(3, 1)